# Generated by Django 5.2.6 on 2025-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_personalinfo_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='cropping',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image_position',
            field=models.CharField(choices=[('50% 50%', 'Center'), ('50% 30%', 'Face Up'), ('50% 70%', 'Face Down'), ('30% 50%', 'Shift Right'), ('70% 50%', 'Shift Left'), ('50% 25%', 'Top Focus'), ('50% 75%', 'Bottom Focus')], default='50% 50%', help_text='Choose how to position your face in the circle', max_length=20, verbose_name='Image Position'),
        ),
    ]
