# Generated by Django 5.2.6 on 2025-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_personalinfo_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='image_position',
            field=models.CharField(default='50% 50%', help_text='Position values for the image (automatically set when you drag)', max_length=20, verbose_name='Image Position'),
        ),
    ]
