# Generated by Django 5.2.6 on 2025-09-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_personalinfo_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='image_position',
        ),
    ]
